mixed-port: 7890
allow-lan: true
tcp-concurrent: true
mode: rule
log-level: info
ipv6: false
dns:
enable: true
default-nameserver:
- 223.5.5.5
- 223.6.6.6
- 114.114.114.114
enhanced-mode: redir-host
fake-ip-range: 28.0.0.1/8
use-hosts: true
nameserver:
- "https://223.5.5.5/dns-query"
- https://doh.pub/dns-query
fallback:
- "https://1.1.1.1/dns-query"
- tls://dns.google
fallback-filter:
  geosite:
    - gfw
  geoip: true 
  geoip-code: CN 
  ipcidr:
    - 240.0.0.0/4
  domain:
    - '+.google.com'
    - '+.youtube.com'

proxy-server-nameserver:
- 223.5.5.5
- 223.6.6.6
- "https://223.5.5.5/dns-query"

proxies:
  - {"name": "Warp1","type":"wireguard","server": "188.114.98.73","port": 891,"ip":"172.16.0.2","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"oJDoX3XycAEs7GAMxWR8iq7egbTVa3aqsLdbv7dDl0E=","mtu":1280,"udp":true,"remote-dns-resolve": true,"dns":[ 1.1.1.1, 8.8.8.8 ]}

rules:
  - GEOSITE,gfw,Warp1
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,apple,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Warp1