mixed-port: 7890
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5
ntp:
  enable: true
  write-to-system: true
  server: ntp.aliyun.com
  port: 123
  interval: 300

proxies:
  - {"name":"jump","type":"vmess","server":"127.0.0.1","port":333,"cipher":"auto","uuid":"94242109-0930-427f-f899-15d34021130c","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/","headers":{"host":"eu.org"}}}
  - {"name":"p3","type":"vmess","server":"us2a-20250420.deepgpt.top","port":80,"cipher":"auto","uuid":"c97cf46e-1554-36cb-8b36-c3556b883dc4","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/windows8","v2ray-http-upgrade":true,"v2ray-http-upgrade-fast-open":true}}
  - name: uk01
    type: vless
    server: uk-001.xiaoxiaobujidao.xyz
    port: 443
    flow: xtls-rprx-vision
    udp: true
    uuid: 5b851213-e004-4302-8994-f5912d763951
    alterId: 0
    cipher: auto
    network: tcp
    ws-opts:
      path: /bujidao
      headers:
        Host: uk-001.xiaoxiaobujidao.xyz
    ws-path: /bujidao
    ws-headers:
      Host: uk-001.xiaoxiaobujidao.xyz
    tls: true
    servername: dash.cloudflare.com
    client-fingerprint: firefox
    reality-opts:
      public-key: vMHW4_fx7bd_4bFZN9ecx58xSjv6SLg0wRYrdI62yUo
      short-id: ""
  - {"name":"hy1a","type":"hysteria","server":"195.154.200.40","port":"15010","sni":"www.bing.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":50,"down":50}
  - {"name":"hy1b","type":"hysteria","server":"62.210.10.113","port":13767,"sni":"apple.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":11,"down":55}
  - {"name":"hy1c","type":"hysteria","server":"62.210.127.217","port":"50011","sni":"www.bing.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":50,"down":50}
  - {"name":"用太快会断开几小时","type":"hysteria2","server":"starlink-us2.2513142.xyz","port":25131,"password":"BHx6lJyJoAFvQ1ZXb4pMs23R","sni":"www.cloudflare.com","skip-cert-verify":true}
  - {"name":"imalrzai","type":"trojan","server":"15.204.248.103","port":443,"password":"b57b594d-9ac4-4f94-834f-092a422f2ef7","tls":true,"sni":"rs3.freeguard.org","skip-cert-verify":true,"network":"tcp"}
  - {"name":"dpdns","server":"51.83.4.33","port":24220,"type":"vless","uuid":"336a38b9-6107-485a-a062-6162985c4b2d","tls":true,"tfo":false,"skip-cert-verify":true,"reality-opts":{"public-key":"x2kWGnpn4JHmqY1y-nyAZvhgvnoXRu1CECo2S6wutm0","short-id":"6c78c2b5178ca4"},"client-fingerprint":"chrome","network":"tcp","servername":"icloud.com"}

proxy-groups:
  - name: 代理
    type: url-test
    url: "https://dongtaiwang.com/generate_204"
    interval: 3000
    tolerance: 150
    lazy: true
    disable-udp: true
    proxies:
      - jump
      - p3
      - uk01
      - hy1a
      - hy1b
      - hy1c
      - 用太快会断开几小时
      - imalrzai
      - dpdns

rules:
  - DOMAIN-KEYWORD,tiandix,代理
  - DOMAIN-KEYWORD,gongyi,代理
  - DOMAIN-KEYWORD,shenyun,代理
  - DOMAIN-KEYWORD,falun,代理
  - DOMAIN-KEYWORD,minghui,代理
  - DOMAIN-KEYWORD,zhengjian,代理
  - DOMAIN-KEYWORD,epoch,代理
  - DOMAIN-KEYWORD,ntdtv,代理
  - DOMAIN-KEYWORD,soundofhope,代理
  - DOMAIN-KEYWORD,secretchina,代理
  - DOMAIN-KEYWORD,ippotv,代理
  - DOMAIN-KEYWORD,ganjing,代理
  - DOMAIN-KEYWORD,ticketing,代理
  - DOMAIN-KEYWORD,fayuan,代理
  - DOMAIN-KEYWORD,mhwindow,代理
  - DOMAIN-KEYWORD,newsancai,代理
  - DOMAIN-KEYWORD,dongtaiwang,代理
  - DOMAIN-KEYWORD,safechat,代理
  - DOMAIN-KEYWORD,freedom,代理
  - DOMAIN-KEYWORD,ming-jian,代理
  - DOMAIN-KEYWORD,youmaker,代理
  - DOMAIN-KEYWORD,recaptcha,代理
  - DOMAIN-KEYWORD,tuta,代理
  - DOMAIN-KEYWORD,rightdao,代理
  - DOMAIN-KEYWORD,proton,代理
  - DOMAIN-KEYWORD,cloudokyo,代理
  - DOMAIN-KEYWORD,edgefare,DIRECT
  - DOMAIN-KEYWORD,wikipedia,代理
  - DOMAIN-KEYWORD,github,代理
  - GEOSITE,falungong,代理
  - GEOSITE,google,代理
  - GEOSITE,github,代理
  - GEOSITE,yahoo,代理
  - GEOSITE,microsoft,DIRECT
  - GEOSITE,win-update,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,icloud,DIRECT
  - GEOSITE,nvidia,DIRECT
  - GEOSITE,acer,DIRECT
  - GEOSITE,amd,DIRECT
  - GEOSITE,asus,DIRECT
  - GEOSITE,dell,DIRECT
  - GEOSITE,hp,DIRECT
  - GEOSITE,cloudflare,DIRECT
  - GEOSITE,private,DIRECT
  - MATCH,REJECT
