mixed-port: 7890
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - tls://dns.opendns.com:853
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5

proxies:
  - name: Warp1
    server: 35.186.245.55
    port: 443
    type: trojan
    password: a5f12cce-f3a1-4818-900c-e3f374a1df5d
    sni: microstation.deeptang.repl.co
    skip-cert-verify: true
    udp: true
    tls: true
    network: ws
    ws-opts:
         path: "/tr?ed2049"
         headers:
            Host: microstation.deeptang.repl.co

rules:
  - GEOSITE,gfw,Warp1
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,apple,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Warp1