mixed-port: 7890
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - tls://dns.opendns.com:853
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5

proxies:
  - name: Warp1
    type: hysteria
    server: 173.234.25.52
    port: 20164
    protocol: udp
    up: "900 Mbps"
    down: "900 Mbps"
    auth_str: Ljg6NNEATDqP97hdAdHe1lJv7ggtKc0h7zmCCZKCX3qY0LR64F
    sni: www.microsoft.com
    skip-cert-verify: true

rules:
  - GEOSITE,gfw,Warp1
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,apple,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Warp1
