mixed-port: 7890
allow-lan: true
tcp-concurrent: true
mode: rule
log-level: info
# ipv6: false
dns:
enable: true
default-nameserver:
- 223.5.5.5
- 223.6.6.6
- 114.114.114.114
enhanced-mode: redir-host
fake-ip-range: 28.0.0.1/8
use-hosts: true
nameserver:
- "https://223.5.5.5/dns-query"
- https://doh.pub/dns-query
fallback:
- "https://1.1.1.1/dns-query"
- tls://dns.google
fallback-filter:
  geosite:
    - gfw
  geoip: true 
  geoip-code: CN 
  ipcidr:
    - 240.0.0.0/4
  domain:
    - '+.google.com'
    - '+.youtube.com'

proxy-server-nameserver:
- 223.5.5.5
- 223.6.6.6
- "https://223.5.5.5/dns-query"

proxies: 
  - name: Warp1
    server: microstation.deeptang.repl.co
    port: 443
    type: trojan
    password: a5f12cce-f3a1-4818-900c-e3f374a1df5d
    sni: microstation.deeptang.repl.co
    skip-cert-verify: true
    udp: true
    tls: true
    network: ws
    ws-opts:
         path: "/tr?ed2049"
         headers:
            Host: microstation.deeptang.repl.co

rules:
  - GEOSITE,gfw,Warp1
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,apple,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Warp1