mixed-port: 7890
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5
ntp:
  enable: true
  write-to-system: true
  server: ntp.aliyun.com
  port: 123
  interval: 300

proxies:
  - {"name":"jump","type":"vmess","server":"127.0.0.1","port":333,"cipher":"auto","uuid":"94242109-0930-427f-f899-15d34021130c","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/","headers":{"host":"eu.org"}}}
  - {"name":"p4","type":"trojan","server":"us1t-1022.88888009.xyz","port":443,"udp":true,"password":"2b6813ab-12c6-304e-9d55-640f7c6070c9","skip-cert-verify":true,"network":"ws","ws-opts":{"path":"/3690dc09-26c3-57ab-b9cf-836523956698"}}
  - {"name":"hy1a","type":"hysteria","server":"64.42.176.179","port":"19513","sni":"www.bing.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":50,"down":50}
  - {"name":"reality1_alvin","type":"vless","server":"45.150.165.121","port":7885,"udp":true,"uuid":"82f6a148-5c4a-48f9-931a-e3b26777ffa2","tls":true,"servername":"www.yahoo.com","flow":"xtls-rprx-vision","network":"tcp","reality-opts":{"public-key":"cauu7I7nFMqzwMDdULVRJam0T04U4knX8koK0OG5dC8","short-id":"40cb281a"},"client-fingerprint":"chrome"}
  - {"name":"reality2_alvin","type":"vless","server":"64.42.176.180","port":44008,"udp":true,"uuid":"7c90a89e-63b3-4d40-90c6-1b5f1aa14e38","tls":true,"servername":"nijigen-works.jp","flow":"xtls-rprx-vision","network":"tcp","reality-opts":{"public-key":"EdE36arx2ZEamAp3e60zvwSdcrCr4CU9HI5bFTvh9W0","short-id":"fada62ff6504c59a"},"client-fingerprint":"chrome"}
  - {"name":"ca","type":"vless","server":"carmelo.ns.cloudflare.com","port":80,"uuid":"571f64c7-bff0-4d33-8765-56ad2334cb55","servername":"ca.ailicf.us.kg","network":"ws","ws-opts":{"path":"/ascb","headers":{"host":"ca.ailicf.us.kg"}}}
  - {"name":"us-shx","type":"vless","server":"188.42.145.140","port":443,"udp":true,"uuid":"f3fcb0be-c785-4791-bd88-335dd20f0c1e","tls":true,"servername":"g1.youyuan.us.kg","network":"ws","skip-cert-verify":true,"ws-opts":{"path":"/?proxyip=proxyip.multacom.fxxk.dedyn.iofp=chromefp=chrome","headers":{"host":"g1.youyuan.us.kg"}}}
  - {"name":"hg3","type":"hysteria2","server":"146.56.116.145","port":55228,"password":"b0c9894f-5bc7-4475-974f-7d9889d2dcef","sni":"bing.com","skip-cert-verify":true}
  - name: warp1
    type: wireguard
    server: 188.114.98.73
    port: 891
    ip: 172.16.0.2
    public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
    private-key: oJDoX3XycAEs7GAMxWR8iq7egbTVa3aqsLdbv7dDl0E=
    mtu: 1280
    udp: true
    remote-dns-resolve: true
    dns: [ 1.1.1.1, 8.8.8.8 ]
    dialer-proxy: hg3

proxy-groups:
  - name: 代理
    type: url-test
    url: "https://dongtaiwang.com/generate_204"
    interval: 5000
    tolerance: 150
    lazy: true
    disable-udp: true
    proxies:
      - jump
      - p4
      - hy1a
      - us-shx
      - reality1_alvin
      - reality2_alvin
      - ca
      - warp1

rules:
  - DOMAIN-KEYWORD,tiandix,代理
  - DOMAIN-KEYWORD,gongyi,代理
  - DOMAIN-KEYWORD,shenyun,代理
  - DOMAIN-KEYWORD,falun,代理
  - DOMAIN-KEYWORD,minghui,代理
  - DOMAIN-KEYWORD,zhengjian,代理
  - DOMAIN-KEYWORD,epoch,代理
  - DOMAIN-KEYWORD,ntdtv,代理
  - DOMAIN-KEYWORD,soundofhope,代理
  - DOMAIN-KEYWORD,secretchina,代理
  - DOMAIN-KEYWORD,ippotv,代理
  - DOMAIN-KEYWORD,ganjing,代理
  - DOMAIN-KEYWORD,ticketing,代理
  - DOMAIN-KEYWORD,fayuan,代理
  - DOMAIN-KEYWORD,mhwindow,代理
  - DOMAIN-KEYWORD,newsancai,代理
  - DOMAIN-KEYWORD,dongtaiwang,代理
  - DOMAIN-KEYWORD,safechat,代理
  - DOMAIN-KEYWORD,freedom,代理
  - DOMAIN-KEYWORD,ming-jian,代理
  - DOMAIN-KEYWORD,youmaker,代理
  - DOMAIN-KEYWORD,recaptcha,代理
  - DOMAIN-KEYWORD,tuta,代理
  - DOMAIN-KEYWORD,rightdao,代理
  - DOMAIN-KEYWORD,proton,代理
  - DOMAIN-KEYWORD,cloudokyo,代理
  - DOMAIN-KEYWORD,edgefare,DIRECT
  - DOMAIN-KEYWORD,wikipedia,代理
  - DOMAIN-KEYWORD,github,代理
  - GEOSITE,falungong,代理
  - GEOSITE,google,代理
  - GEOSITE,github,代理
  - GEOSITE,yahoo,代理
  - GEOSITE,microsoft,DIRECT
  - GEOSITE,win-update,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,icloud,DIRECT
  - GEOSITE,nvidia,DIRECT
  - GEOSITE,acer,DIRECT
  - GEOSITE,amd,DIRECT
  - GEOSITE,asus,DIRECT
  - GEOSITE,dell,DIRECT
  - GEOSITE,hp,DIRECT
  - GEOSITE,cloudflare,DIRECT
  - GEOSITE,private,DIRECT
  - MATCH,REJECT
