mixed-port: 7890
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5
ntp:
  enable: true
  write-to-system: true
  server: ntp.aliyun.com
  port: 123
  interval: 300

proxies:
  - {"name":"jump","type":"vmess","server":"127.0.0.1","port":333,"cipher":"auto","uuid":"94242109-0930-427f-f899-15d34021130c","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/","headers":{"host":"eu.org"}}}
  - {"name":"p4","type":"trojan","server":"us2t-videos.88888803.xyz","port":443,"udp":true,"password":"2b6813ab-12c6-304e-9d55-640f7c6070c9","skip-cert-verify":true,"network":"ws","ws-opts":{"path":"/3690dc09-26c3-57ab-b9cf-836523956698"}}
  - {name: us-hy2, type: hysteria2, server: us.xn--wtq35pfyd55o.club, port: 30219, udp: true, skip-cert-verify: true, sni: 1231231.1234567890spcloud.com, password: f04cea95-893d-4e7e-9e34-4bc032315781}
  - {"name":"hy2a","type":"hysteria2","server":"51.159.77.153","port":33390,"password":"dongtaiwang.com","sni":"bing.com","skip-cert-verify":true}
  - {"name":"hy2b","type":"hysteria2","server":"62.210.103.0","port":22483,"password":"dongtaiwang.com","sni":"www.bing.com","skip-cert-verify":true}
  - {"name":"v6","type":"vmess","server":"172.64.99.22","port":2086,"cipher":"auto","uuid":"e9e3cc13-db48-4cc1-8c24-7626439a5339","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"github.com/Alvin9999","headers":{"host":"ip14.freegradely.xyz"}}}
  - {"name":"6222","type":"ss","server":"gy.666666222.shop","port":20015,"password":"4bc910e3-7ccd-4f27-8e8e-abf5c6c34a31","cipher":"chacha20-ietf-poly1305"}

proxy-groups:
  - name: 代理
    type: url-test
    url: "https://dongtaiwang.com/generate_204"
    interval: 5000
    tolerance: 150
    lazy: true
    disable-udp: true
    proxies:
      - jump
      - p4
      - us-hy2
      - hy2a
      - hy2b
      - v6
      - 6222

rules:
  - DOMAIN-KEYWORD,tiandix,代理
  - DOMAIN-KEYWORD,gongyi,代理
  - DOMAIN-KEYWORD,shenyun,代理
  - DOMAIN-KEYWORD,falun,代理
  - DOMAIN-KEYWORD,minghui,代理
  - DOMAIN-KEYWORD,zhengjian,代理
  - DOMAIN-KEYWORD,epoch,代理
  - DOMAIN-KEYWORD,ntdtv,代理
  - DOMAIN-KEYWORD,soundofhope,代理
  - DOMAIN-KEYWORD,secretchina,代理
  - DOMAIN-KEYWORD,ippotv,代理
  - DOMAIN-KEYWORD,ganjing,代理
  - DOMAIN-KEYWORD,ticketing,代理
  - DOMAIN-KEYWORD,fayuan,代理
  - DOMAIN-KEYWORD,mhwindow,代理
  - DOMAIN-KEYWORD,newsancai,代理
  - DOMAIN-KEYWORD,dongtaiwang,代理
  - DOMAIN-KEYWORD,safechat,代理
  - DOMAIN-KEYWORD,freedom,代理
  - DOMAIN-KEYWORD,ming-jian,代理
  - DOMAIN-KEYWORD,youmaker,代理
  - DOMAIN-KEYWORD,recaptcha,代理
  - DOMAIN-KEYWORD,tuta,代理
  - DOMAIN-KEYWORD,rightdao,代理
  - DOMAIN-KEYWORD,proton,代理
  - DOMAIN-KEYWORD,cloudokyo,代理
  - DOMAIN-KEYWORD,edgefare,DIRECT
  - DOMAIN-KEYWORD,wikipedia,代理
  - DOMAIN-KEYWORD,github,代理
  - GEOSITE,falungong,代理
  - GEOSITE,google,代理
  - GEOSITE,github,代理
  - GEOSITE,yahoo,代理
  - GEOSITE,microsoft,DIRECT
  - GEOSITE,win-update,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,icloud,DIRECT
  - GEOSITE,nvidia,DIRECT
  - GEOSITE,acer,DIRECT
  - GEOSITE,amd,DIRECT
  - GEOSITE,asus,DIRECT
  - GEOSITE,dell,DIRECT
  - GEOSITE,hp,DIRECT
  - GEOSITE,cloudflare,DIRECT
  - GEOSITE,private,DIRECT
  - MATCH,REJECT
