mixed-port: 7890
allow-lan: true
tcp-concurrent: true
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  nameserver:
    - 223.5.5.5
    - 114.114.115.115
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5

proxies:
  - name: Warp1
    type: hysteria2
    server: 167.160.90.252
    port: 60930
    up: "900 Mbps"
    down: "900 Mbps"
    password: fc4488ef
    sni: www.bing.com
    skip-cert-verify: true

rules:
  - GEOSITE,gfw,Warp1
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,apple,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Warp1