mixed-port: 7890
# external-controller: 0.0.0.0:9090
mode: rule
log-level: info
ipv6: true
dns:
  enable: true
  ipv6: true
  ipv6-timeout: 300
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  default-nameserver: 
    - 223.5.5.5
  nameserver:
    - quic://dns.adguard.com
    - tls://dns.cleanbrowsing.org
    - tls://dns.opendns.com
  proxy-server-nameserver:
    - 208.67.220.220
    - 223.5.5.5
ntp:
  enable: true
  write-to-system: true
  server: ntp.aliyun.com
  port: 123
  interval: 300

proxies:
  - {"name":"jump","type":"vmess","server":"127.0.0.1","port":333,"cipher":"auto","uuid":"94242109-0930-427f-f899-15d34021130c","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/","headers":{"host":"eu.org"}}}
  - {"name":"Hys1-6","type":"hysteria","server":"173.234.25.52","port":20164,"sni":"www.microsoft.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"Ljg6NNEATDqP97hdAdHe1lJv7ggtKc0h7zmCCZKCX3qY0LR64F","up":600,"down":900}
  - {"name":"rep","type":"trojan","server":"34.100.212.184","port":443,"udp":true,"password":"a5f12cce-f3a1-4818-900c-e3f374a1df5d","sni":"Microstation.Deeptang.repl.co","skip-cert-verify":true,"network":"ws","ws-opts":{"path":"/tr?ed=2048","headers":{"host":"Microstation.Deeptang.repl.co"}}}
  - { name: 新加坡-hy2-04, server: sg.xn--wtq35pfyd55o.club, port: 20129, udp: true, skip-cert-verify: true, sni: 1231231.1234567890spcloud.com, type: hysteria2, password: f04cea95-893d-4e7e-9e34-4bc032315781 }
  - { name: 美国-hy2-05, server: us.xn--wtq35pfyd55o.club, port: 30219, udp: true, skip-cert-verify: true, sni: 1231231.1234567890spcloud.com, type: hysteria2, password: f04cea95-893d-4e7e-9e34-4bc032315781 }
  - {"name":"meta_hysteria_91","type":"hysteria","server":"www.dtku50.xyz","port":23577,"sni":"www.amazon.cn","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":600,"down":900}
  - {"name": "Warp1","type":"wireguard","server": "188.114.98.73","port": 891,"ip":"172.16.0.2","public-key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","private-key":"oJDoX3XycAEs7GAMxWR8iq7egbTVa3aqsLdbv7dDl0E=","mtu":1280,"udp":true,"remote-dns-resolve": true,"dns":[ 1.1.1.1, 8.8.8.8 ]}
  - {"name":"meta_hysteria_81","type":"hysteria","server":"62.204.54.81","port":46333,"sni":"bing.com","skip-cert-verify":true,"alpn":["h3"],"auth_str":"dongtaiwang.com","up":600,"down":900}
  - {"name":"dtw3","type":"vless","server":"23.227.38.108","port":443,"uuid":"0773256c-d020-436d-afea-6eee7cb6c872","tls":true,"servername":"xray1.freegradely.xyz","network":"ws","ws-opts":{"path":"/bodhws?ed=2048","headers":{"host":"xray1.freegradely.xyz"}},"client-fingerprint":"chrome"}
  - {"name":"捷克V2CROSS","type":"vmess","server":"109.123.230.157","port":80,"cipher":"auto","uuid":"877aa2a8-5854-4cb2-9aba-4a1413a6b2de","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"","network":"ws","ws-opts":{"path":"/takeshi.wiki?ed=2048","headers":{"host":"dl.kgvn.garenanow.com"}}}

proxy-groups:
  - name: 代理
    type: url-test
    url: "https://www.gstatic.com/generate_204"
    interval: 5000
    tolerance: 150
    lazy: true
    disable-udp: true
    proxies:
      - jump
      - Hys1-6
      - rep
      - 新加坡-hy2-04
      - 美国-hy2-05
      - meta_hysteria_91
      - Warp1
      - meta_hysteria_81
      - dtw3
      - 捷克V2CROSS

rules:
  - GEOSITE,gfw,代理
  - DOMAIN-KEYWORD,tiandix,代理
  - DOMAIN-KEYWORD,gongyi,代理
  - DOMAIN-KEYWORD,shenyun,代理
  - DOMAIN-KEYWORD,falun,代理
  - DOMAIN-KEYWORD,minghui,代理
  - DOMAIN-KEYWORD,ganjing,代理
  - GEOIP,private,DIRECT
  - GEOIP,CN,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,63.92.224.0/19,DIRECT,no-resolve
  - IP-CIDR,65.199.22.0/23,DIRECT,no-resolve
  - IP-CIDR,139.178.128.0/18,DIRECT,no-resolve
  - IP-CIDR,144.178.0.0/19,DIRECT,no-resolve
  - IP-CIDR,144.178.36.0/22,DIRECT,no-resolve
  - IP-CIDR,144.178.48.0/20,DIRECT,no-resolve
  - IP-CIDR,192.35.50.0/24,DIRECT,no-resolve
  - IP-CIDR,198.183.17.0/24,DIRECT,no-resolve
  - IP-CIDR,205.180.175.0/24,DIRECT,no-resolve
# 中国云服务商ip端
  - IP-CIDR,8.128.0.0/10,DIRECT,no-resolve
  - IP-CIDR,8.208.0.0/12,DIRECT,no-resolve
  - IP-CIDR,14.1.112.0/22,DIRECT,no-resolve
  - IP-CIDR,41.222.240.0/22,DIRECT,no-resolve
  - IP-CIDR,41.223.119.0/24,DIRECT,no-resolve
  - IP-CIDR,43.242.168.0/22,DIRECT,no-resolve
  - IP-CIDR,45.112.212.0/22,DIRECT,no-resolve
  - IP-CIDR,47.52.0.0/16,DIRECT,no-resolve
  - IP-CIDR,47.56.0.0/15,DIRECT,no-resolve
  - IP-CIDR,47.74.0.0/15,DIRECT,no-resolve
  - IP-CIDR,47.76.0.0/14,DIRECT,no-resolve
  - IP-CIDR,47.80.0.0/12,DIRECT,no-resolve
  - IP-CIDR,47.235.0.0/16,DIRECT,no-resolve
  - IP-CIDR,47.236.0.0/14,DIRECT,no-resolve
  - IP-CIDR,47.240.0.0/14,DIRECT,no-resolve
  - IP-CIDR,47.244.0.0/15,DIRECT,no-resolve
  - IP-CIDR,47.246.0.0/16,DIRECT,no-resolve
  - IP-CIDR,47.250.0.0/15,DIRECT,no-resolve
  - IP-CIDR,47.252.0.0/15,DIRECT,no-resolve
  - IP-CIDR,47.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,59.82.0.0/20,DIRECT,no-resolve
  - IP-CIDR,59.82.240.0/21,DIRECT,no-resolve
  - IP-CIDR,59.82.248.0/22,DIRECT,no-resolve
  - IP-CIDR,72.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,103.38.56.0/22,DIRECT,no-resolve
  - IP-CIDR,103.52.76.0/22,DIRECT,no-resolve
  - IP-CIDR,103.206.40.0/22,DIRECT,no-resolve
  - IP-CIDR,110.76.21.0/24,DIRECT,no-resolve
  - IP-CIDR,110.76.23.0/24,DIRECT,no-resolve
  - IP-CIDR,112.125.0.0/17,DIRECT,no-resolve
  - IP-CIDR,116.251.64.0/18,DIRECT,no-resolve
  - IP-CIDR,119.38.208.0/20,DIRECT,no-resolve
  - IP-CIDR,119.38.224.0/20,DIRECT,no-resolve
  - IP-CIDR,119.42.224.0/20,DIRECT,no-resolve
  - IP-CIDR,139.95.0.0/16,DIRECT,no-resolve
  - IP-CIDR,140.205.1.0/24,DIRECT,no-resolve
  - IP-CIDR,140.205.122.0/24,DIRECT,no-resolve
  - IP-CIDR,147.139.0.0/16,DIRECT,no-resolve
  - IP-CIDR,149.129.0.0/16,DIRECT,no-resolve
  - IP-CIDR,155.102.0.0/16,DIRECT,no-resolve
  - IP-CIDR,161.117.0.0/16,DIRECT,no-resolve
  - IP-CIDR,163.181.0.0/16,DIRECT,no-resolve
  - IP-CIDR,170.33.0.0/16,DIRECT,no-resolve
  - IP-CIDR,198.11.128.0/18,DIRECT,no-resolve
  - IP-CIDR,205.204.96.0/19,DIRECT,no-resolve
  - IP-CIDR,19.28.0.0/23,DIRECT,no-resolve
  - IP-CIDR,45.40.192.0/19,DIRECT,no-resolve
  - IP-CIDR,49.51.0.0/16,DIRECT,no-resolve
  - IP-CIDR,62.234.0.0/16,DIRECT,no-resolve
  - IP-CIDR,94.191.0.0/17,DIRECT,no-resolve
  - IP-CIDR,103.7.28.0/22,DIRECT,no-resolve
  - IP-CIDR,103.116.50.0/23,DIRECT,no-resolve
  - IP-CIDR,103.231.60.0/24,DIRECT,no-resolve
  - IP-CIDR,109.244.0.0/16,DIRECT,no-resolve
  - IP-CIDR,111.30.128.0/21,DIRECT,no-resolve
  - IP-CIDR,111.30.136.0/24,DIRECT,no-resolve
  - IP-CIDR,111.30.139.0/24,DIRECT,no-resolve
  - IP-CIDR,111.30.140.0/23,DIRECT,no-resolve
  - IP-CIDR,115.159.0.0/16,DIRECT,no-resolve
  - IP-CIDR,119.28.0.0/15,DIRECT,no-resolve
  - IP-CIDR,120.88.56.0/23,DIRECT,no-resolve
  - IP-CIDR,121.51.0.0/16,DIRECT,no-resolve
  - IP-CIDR,129.28.0.0/16,DIRECT,no-resolve
  - IP-CIDR,129.204.0.0/16,DIRECT,no-resolve
  - IP-CIDR,129.211.0.0/16,DIRECT,no-resolve
  - IP-CIDR,132.232.0.0/16,DIRECT,no-resolve
  - IP-CIDR,134.175.0.0/16,DIRECT,no-resolve
  - IP-CIDR,146.56.192.0/18,DIRECT,no-resolve
  - IP-CIDR,148.70.0.0/16,DIRECT,no-resolve
  - IP-CIDR,150.109.0.0/16,DIRECT,no-resolve
  - IP-CIDR,152.136.0.0/16,DIRECT,no-resolve
  - IP-CIDR,162.14.0.0/16,DIRECT,no-resolve
  - IP-CIDR,162.62.0.0/16,DIRECT,no-resolve
  - IP-CIDR,170.106.130.0/24,DIRECT,no-resolve
  - IP-CIDR,182.254.0.0/16,DIRECT,no-resolve
  - IP-CIDR,188.131.128.0/17,DIRECT,no-resolve
  - IP-CIDR,203.195.128.0/17,DIRECT,no-resolve
  - IP-CIDR,203.205.128.0/17,DIRECT,no-resolve
  - IP-CIDR,210.4.138.0/24,DIRECT,no-resolve
  - IP-CIDR,211.152.128.0/23,DIRECT,no-resolve
  - IP-CIDR,211.152.132.0/23,DIRECT,no-resolve
  - IP-CIDR,211.152.148.0/23,DIRECT,no-resolve
  - IP-CIDR,212.64.0.0/17,DIRECT,no-resolve
  - IP-CIDR,212.129.128.0/17,DIRECT,no-resolve
  - IP-CIDR,45.113.192.0/22,DIRECT,no-resolve
  - IP-CIDR,63.217.23.0/24,DIRECT,no-resolve
  - IP-CIDR,63.243.252.0/24,DIRECT,no-resolve
  - IP-CIDR,103.235.44.0/22,DIRECT,no-resolve
  - IP-CIDR,104.193.88.0/22,DIRECT,no-resolve
  - IP-CIDR,106.12.0.0/15,DIRECT,no-resolve
  - IP-CIDR,114.28.224.0/20,DIRECT,no-resolve
  - IP-CIDR,119.63.192.0/21,DIRECT,no-resolve
  - IP-CIDR,180.76.0.0/24,DIRECT,no-resolve
  - IP-CIDR,180.76.0.0/16,DIRECT,no-resolve
  - IP-CIDR,182.61.0.0/16,DIRECT,no-resolve
  - IP-CIDR,185.10.104.0/22,DIRECT,no-resolve
  - IP-CIDR,202.46.48.0/20,DIRECT,no-resolve
  - IP-CIDR,203.90.238.0/24,DIRECT,no-resolve
  - IP-CIDR,43.254.0.0/22,DIRECT,no-resolve
  - IP-CIDR,45.249.212.0/22,DIRECT,no-resolve
  - IP-CIDR,49.4.0.0/17,DIRECT,no-resolve
  - IP-CIDR,78.101.192.0/19,DIRECT,no-resolve
  - IP-CIDR,78.101.224.0/20,DIRECT,no-resolve
  - IP-CIDR,81.52.161.0/24,DIRECT,no-resolve
  - IP-CIDR,85.97.220.0/22,DIRECT,no-resolve
  - IP-CIDR,103.31.200.0/22,DIRECT,no-resolve
  - IP-CIDR,103.69.140.0/23,DIRECT,no-resolve
  - IP-CIDR,103.218.216.0/22,DIRECT,no-resolve
  - IP-CIDR,114.115.128.0/17,DIRECT,no-resolve
  - IP-CIDR,114.116.0.0/16,DIRECT,no-resolve
  - IP-CIDR,116.63.128.0/18,DIRECT,no-resolve
  - IP-CIDR,116.66.184.0/22,DIRECT,no-resolve
  - IP-CIDR,116.71.96.0/20,DIRECT,no-resolve
  - IP-CIDR,116.71.128.0/21,DIRECT,no-resolve
  - IP-CIDR,116.71.136.0/22,DIRECT,no-resolve
  - IP-CIDR,116.71.141.0/24,DIRECT,no-resolve
  - IP-CIDR,116.71.142.0/24,DIRECT,no-resolve
  - IP-CIDR,116.71.243.0/24,DIRECT,no-resolve
  - IP-CIDR,116.71.244.0/24,DIRECT,no-resolve
  - IP-CIDR,116.71.251.0/24,DIRECT,no-resolve
  - IP-CIDR,117.78.0.0/18,DIRECT,no-resolve
  - IP-CIDR,119.3.0.0/16,DIRECT,no-resolve
  - IP-CIDR,119.8.0.0/21,DIRECT,no-resolve
  - IP-CIDR,119.8.32.0/19,DIRECT,no-resolve
  - IP-CIDR,121.36.0.0/17,DIRECT,no-resolve
  - IP-CIDR,121.36.128.0/18,DIRECT,no-resolve
  - IP-CIDR,121.37.0.0/17,DIRECT,no-resolve
  - IP-CIDR,122.112.128.0/17,DIRECT,no-resolve
  - IP-CIDR,139.9.0.0/18,DIRECT,no-resolve
  - IP-CIDR,139.9.64.0/19,DIRECT,no-resolve
  - IP-CIDR,139.9.100.0/22,DIRECT,no-resolve
  - IP-CIDR,139.9.104.0/21,DIRECT,no-resolve
  - IP-CIDR,139.9.112.0/20,DIRECT,no-resolve
  - IP-CIDR,139.9.128.0/18,DIRECT,no-resolve
  - IP-CIDR,139.9.192.0/19,DIRECT,no-resolve
  - IP-CIDR,139.9.224.0/20,DIRECT,no-resolve
  - IP-CIDR,139.9.240.0/21,DIRECT,no-resolve
  - IP-CIDR,139.9.248.0/22,DIRECT,no-resolve
  - IP-CIDR,139.159.128.0/19,DIRECT,no-resolve
  - IP-CIDR,139.159.160.0/22,DIRECT,no-resolve
  - IP-CIDR,139.159.164.0/23,DIRECT,no-resolve
  - IP-CIDR,139.159.168.0/21,DIRECT,no-resolve
  - IP-CIDR,139.159.176.0/20,DIRECT,no-resolve
  - IP-CIDR,139.159.192.0/18,DIRECT,no-resolve
  - IP-CIDR,159.138.0.0/18,DIRECT,no-resolve
  - IP-CIDR,159.138.64.0/21,DIRECT,no-resolve
  - IP-CIDR,159.138.79.0/24,DIRECT,no-resolve
  - IP-CIDR,159.138.80.0/20,DIRECT,no-resolve
  - IP-CIDR,159.138.96.0/20,DIRECT,no-resolve
  - IP-CIDR,159.138.112.0/21,DIRECT,no-resolve
  - IP-CIDR,159.138.125.0/24,DIRECT,no-resolve
  - IP-CIDR,159.138.128.0/18,DIRECT,no-resolve
  - IP-CIDR,159.138.192.0/20,DIRECT,no-resolve
  - IP-CIDR,159.138.223.0/24,DIRECT,no-resolve
  - IP-CIDR,159.138.224.0/19,DIRECT,no-resolve
  - IP-CIDR,168.195.92.0/22,DIRECT,no-resolve
  - IP-CIDR,185.176.76.0/22,DIRECT,no-resolve
  - IP-CIDR,197.199.0.0/18,DIRECT,no-resolve
  - IP-CIDR,197.210.163.0/24,DIRECT,no-resolve
  - IP-CIDR,197.252.1.0/24,DIRECT,no-resolve
  - IP-CIDR,197.252.2.0/23,DIRECT,no-resolve
  - IP-CIDR,197.252.4.0/22,DIRECT,no-resolve
  - IP-CIDR,197.252.8.0/21,DIRECT,no-resolve
  - IP-CIDR,200.32.52.0/24,DIRECT,no-resolve
  - IP-CIDR,200.32.54.0/24,DIRECT,no-resolve
  - IP-CIDR,200.32.57.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.0.0/22,DIRECT,no-resolve
  - IP-CIDR,203.135.4.0/23,DIRECT,no-resolve
  - IP-CIDR,203.135.8.0/23,DIRECT,no-resolve
  - IP-CIDR,203.135.11.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.13.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.20.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.22.0/23,DIRECT,no-resolve
  - IP-CIDR,203.135.24.0/23,DIRECT,no-resolve
  - IP-CIDR,203.135.26.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.29.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.33.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.38.0/23,DIRECT,no-resolve
  - IP-CIDR,203.135.40.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.43.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.48.0/24,DIRECT,no-resolve
  - IP-CIDR,203.135.50.0/24,DIRECT,no-resolve
  - IP-CIDR,42.186.0.0/16,DIRECT,no-resolve
  - IP-CIDR,45.127.128.0/22,DIRECT,no-resolve
  - IP-CIDR,45.195.24.0/24,DIRECT,no-resolve
  - IP-CIDR,45.253.132.0/22,DIRECT,no-resolve
  - IP-CIDR,45.253.240.0/22,DIRECT,no-resolve
  - IP-CIDR,45.254.48.0/23,DIRECT,no-resolve
  - IP-CIDR,59.111.0.0/20,DIRECT,no-resolve
  - IP-CIDR,59.111.128.0/17,DIRECT,no-resolve
  - IP-CIDR,103.71.120.0/21,DIRECT,no-resolve
  - IP-CIDR,103.71.128.0/22,DIRECT,no-resolve
  - IP-CIDR,103.71.196.0/22,DIRECT,no-resolve
  - IP-CIDR,103.71.200.0/22,DIRECT,no-resolve
  - IP-CIDR,103.72.12.0/22,DIRECT,no-resolve
  - IP-CIDR,103.72.18.0/23,DIRECT,no-resolve
  - IP-CIDR,103.72.24.0/22,DIRECT,no-resolve
  - IP-CIDR,103.72.28.0/23,DIRECT,no-resolve
  - IP-CIDR,103.72.38.0/23,DIRECT,no-resolve
  - IP-CIDR,103.72.40.0/23,DIRECT,no-resolve
  - IP-CIDR,103.72.44.0/22,DIRECT,no-resolve
  - IP-CIDR,103.72.48.0/21,DIRECT,no-resolve
  - IP-CIDR,103.72.128.0/21,DIRECT,no-resolve
  - IP-CIDR,103.74.24.0/21,DIRECT,no-resolve
  - IP-CIDR,103.74.48.0/22,DIRECT,no-resolve
  - IP-CIDR,103.126.92.0/22,DIRECT,no-resolve
  - IP-CIDR,103.129.252.0/22,DIRECT,no-resolve
  - IP-CIDR,103.131.252.0/22,DIRECT,no-resolve
  - IP-CIDR,103.135.240.0/22,DIRECT,no-resolve
  - IP-CIDR,103.196.64.0/22,DIRECT,no-resolve
  - IP-CIDR,106.2.32.0/19,DIRECT,no-resolve
  - IP-CIDR,106.2.64.0/18,DIRECT,no-resolve
  - IP-CIDR,114.113.196.0/22,DIRECT,no-resolve
  - IP-CIDR,114.113.200.0/22,DIRECT,no-resolve
  - IP-CIDR,115.236.112.0/20,DIRECT,no-resolve
  - IP-CIDR,115.238.76.0/22,DIRECT,no-resolve
  - IP-CIDR,123.58.160.0/19,DIRECT,no-resolve
  - IP-CIDR,223.252.192.0/19,DIRECT,no-resolve
  - IP-CIDR,101.198.128.0/18,DIRECT,no-resolve
  - IP-CIDR,101.198.192.0/19,DIRECT,no-resolve
  - IP-CIDR,101.199.196.0/22,DIRECT,no-resolve
  - MATCH,代理
